const ROWS_SEPARATOR = '\n';
const MAX_RESULTS = 99;
const MAX_SEPARATOR_DETECTING_DATA = 9999;
const LOCAL_STORAGE_ITEM_KEY = 'recentDictionaryItems';

const config = {
	ROWS_SEPARATOR,
	MAX_RESULTS,
	MAX_SEPARATOR_DETECTING_DATA,
	LOCAL_STORAGE_ITEM_KEY
};

export { config };
